chipset = "sm8250"

[bootimg]
version = 2
base = 0x0
bootsize = 0x4000000
kernel = 0x8000
ramdisk = 0x2000000
second = 0
tags = 0x1e00000
dtb = 0x1f00000
pagesize = 0x1000
name = ""
board = "SRPTG02C004"
os_version = "11.0.0"
os_patch_level = "2022-04"

[[device]]
vendor = "samsung"
model = "r8q"
dtb_model_fallbacks = ["r8s"]
append_dtb_to_kernel = false
append = "console=tty0 clk_ignore_unused pd_ignore_unused rootimg=PARTLABEL=userdata/media/0/data/rootfs.img root=/dev/loop0 mobile.root=/dev/loop0"

dtb = "qcom/sm8250-samsung-r8q.dtb"
